# Generated by Django 6.0.7 on 2026-07-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cf_piva', models.CharField(max_length=16, unique=True)),
                ('rag_soc', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(blank=True, max_length=150, null=True)),
                ('citta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('codice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('codice_parlante', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('data', models.DateField()),
                ('imponibile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('stato_pagamento', models.CharField(choices=[('Annullata', 'Annullata'), ('Pagata', 'Pagata'), ('Scaduta', 'Scaduta')], default='Annullata', max_length=15)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('indirizzo_fatturazione', models.CharField(blank=True, max_length=150, null=True)),
                ('citta_fatturazione', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fattura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lettura',
            fields=[
                ('codice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('codice_parlante', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('data', models.DateField()),
                ('valore', models.IntegerField()),
                ('tipo_lettura', models.CharField(choices=[('reale', 'reale'), ('stimata', 'stimata'), ('autolettura', 'autolettura')], default='reale', max_length=15)),
            ],
            options={
                'db_table': 'lettura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoFornitura',
            fields=[
                ('codice_pod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('indirizzo', models.CharField(blank=True, max_length=150, null=True)),
                ('citta', models.CharField(blank=True, max_length=100, null=True)),
                ('distretto', models.CharField(choices=[('Nord-Ovest BG', 'Nord-Ovest BG'), ('Sud-Est BG e BS', 'Sud-Est BG e BS'), ('Brianza', 'Brianza'), ('Lecchese e Lario', 'Lecchese e Lario'), ('Martesana e Cremasco', 'Martesana e Cremasco'), ('Non Definito', 'Non Definito')], default='Non Definito', max_length=30)),
                ('diametro_tubo', models.CharField(blank=True, max_length=20, null=True)),
                ('portata_massima', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'puntofornitura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utenza',
            fields=[
                ('codice', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('codice_parlante', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('data_apertura', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('attiva', 'attiva'), ('inattiva', 'inattiva')], default='attiva', max_length=10)),
                ('data_chiusura', models.DateField(blank=True, null=True)),
                ('tipologia', models.CharField(choices=[('Domestico Residente', 'Domestico Residente'), ('Domestico Non Residente', 'Domestico Non Residente'), ('Commerciale', 'Commerciale'), ('Industriale', 'Industriale')], max_length=30)),
                ('componenti_nucleo', models.IntegerField(blank=True, null=True)),
                ('indirizzo_fatturazione', models.CharField(blank=True, max_length=150, null=True)),
                ('citta_fatturazione', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'utenza',
                'managed': False,
            },
        ),
    ]
