"""
Django settings for webservice_locale project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kvin+&@k=%3192xn-6y$2gtv%ze68!rg#4h3xbch11q78%@%r_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# Rimosse le app di default di Django (admin, auth, contenttypes, sessions,
# messages, staticfiles): sono pensate per applicazioni con utenti, login e
# pagine HTML. Questo progetto e' un web-service puro (nessun utente, nessuna
# pagina), quindi restava solo "api", la nostra applicazione, a usarle davvero.
INSTALLED_APPS = [
    'api',
]

# Rimosse le righe collegate alle app tolte sopra (sessioni, CSRF via form,
# autenticazione utenti, messaggi tra richieste): senza le rispettive app
# installate non avrebbero piu' nulla su cui lavorare. Restano solo le
# protezioni generiche, indipendenti dalle app rimosse.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webservice_locale.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            # Rimossi i context processor di auth e messages (app non piu'
            # installate). Non renderizziamo comunque nessun template in
            # questo progetto, ma il file resta coerente con INSTALLED_APPS.
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'webservice_locale.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS rimosso interamente: serve solo per validare le
# password di un sistema di login utenti, che questo progetto non ha.


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
